version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres

    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres
    restart: always

  main:
    container_name: tm_main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata: